### ISSUE TITLE
Is posible magnestism rotate

### ISSUE THREAD

**Issue by webserveis** [allenxuan/XuanImageView#1]
I like your component, I try to make that when rotating the image it is adjusted vertically or horizontally with the auto rotating effect

That is to say similar that the image is adjusted by rotating the device, but without doing so

And also how to disable the rotation and later activate

**Comment by allenxuan** [comment]
Hey, bro, I may not completely understand what you are trying to describe, pardon me my English.
Question 1: 
"I like your component, I try to make that when rotating the image it is adjusted vertically or horizontally with the auto rotating effect

That is to say similar that the image is adjusted by rotating the device, but without doing so
"

Response:
Do you mean the image is adjusted without it's center overlapping with screen's center?

Question 2:
"And also how to disable the rotation and later activate"

Response:
I've already added a RotationToggle Setter to determine whether rotation function is turned on, you can use it in xml (work for just one time) or in code (recommanded). Just consult the updated README.md.    _(:3 」∠)_

**Comment by webserveis** [comment]
No problem, my English is also poor

I'm thinking of integrating your control into an image gallery viewer, within a viewpage
And I have been able to view images with zoom and magnetic rotation.

To see with the following image we can understand

![magnetic_rotate](https://cloud.githubusercontent.com/assets/2223709/21323650/c62a1d20-c61e-11e6-843c-bd84d94ee720.jpg)

Now
>60º => initial state with autorotation

Magnetic rotate, desactivate autorotation for:

Magentic rotate if device in portrait
>60º => fix the image image as seen simlar a landscape view,

Magentic rotate if device in landscape
>60º => fix the image image as seen a portrait view,

**Comment by allenxuan** [comment]
hey, bro, I will release magnetic rotating function within 12 hours, I'm now debugging it. ^_^

**Comment by allenxuan** [comment]
Bro, I've already release the magnetic rotating function. You can use setAutoRotateCategory() in code or xml. Please consult README.md.  ┐「ε:)_

**Comment by webserveis** [comment]
Awesome
You are the king of the west, how fast it has been!
My test has worked perfect, thank you very much for the implementation
