### ISSUE TITLE
Not work with Glide

### ISSUE THREAD

**Issue by jackypham94** [allenxuan/XuanImageView#2]
I'm trying to done with Glide, but image scale on top and when zoom or double tap, image continue zoom to small. Please fix it :(

**Comment by allenxuan** [comment]
XuanImageView is now compatible with Glide, Picasso and other image loading libraries that use ImageView as container. Please check out version 0.4.0.        _ (:3 」∠) _

**Comment by jackypham94** [comment]
@allenxuan One more bug: If I using XuanImageView with ViewPager for slide image. I can't swipe right or left to view next image ._.

**Comment by allenxuan** [comment]
The demo of this project uses viewpager with XuanImageView, you can check it out and see how it works.  And you should notice that you cannot swipe to the next image within viewpager when current image is not in its initial state (i.e., when current image is either scaled up or scaled down).  The strategy of XuanImageView is just that way.
